### ISSUE TITLE
fails to build proc macro

### ISSUE THREAD

**Issue by romanstingler** [dnut/clipboard-sync#38] opened 2024-07-26 10:50 UTC
```
     stable-x86_64-unknown-linux-gnu updated - rustc 1.80.0 (051478957 2024-07-21) (from rustc 1.77.2 (25ef9e3d8 2024-04-09))
  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.82.0-nightly (7120fdac7 2024-07-25)

info: cleaning up downloads & tmp directories
info: self-update is disabled for this build of rustup
info: any updates to rustup will need to be fetched with your system package manager
/t/clipboard-sync ❯ make                                                                                                                                                                     21.139s (master) 12:50
cargo build --profile "release"
   Compiling proc-macro2 v1.0.47
   Compiling proc-macro-error v1.0.4
   Compiling miniz_oxide v0.4.4
   Compiling num-integer v0.1.44
   Compiling indexmap v1.8.1
   Compiling nix v0.17.0
   Compiling downcast-rs v1.2.0
   Compiling wayland-sys v0.27.0
   Compiling nix v0.22.3
   Compiling libc v0.2.138
   Compiling quick-xml v0.22.0
   Compiling backtrace v0.3.64
   Compiling unicase v2.6.0
   Compiling wayland-sys v0.29.4
   Compiling lazy_static v1.4.0
error[E0635]: unknown feature `proc_macro_span_shrink`
  --> /home/roman/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.47/src/lib.rs:92:30
   |
92 |     feature(proc_macro_span, proc_macro_span_shrink)
   |                              ^^^^^^^^^^^^^^^^^^^^^^

   Compiling io-lifetimes v1.0.3
   Compiling failure_derive v0.1.8
   Compiling adler v1.0.2
   Compiling gimli v0.26.1
   Compiling object v0.27.1
   Compiling term_size v0.3.2
   Compiling atty v0.2.11
For more information about this error, try `rustc --explain E0635`.
error: could not compile `proc-macro2` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
make: *** [Makefile:8: build] Error 101
```

adding 
`proc-macro2 = "1.0.46"` 
to `cargo.toml` fixes it for now

**Comment by dnut** [comment] 2024-09-23 06:46
Did you build with rust nightly? This happens on nightly, but should not happen on stable.

To build once using stable:
```bash
cargo +stable build
```

To permanently set stable as the default:
```bash
rustup default stable
```

**Comment by dnut** [comment] 2024-09-24 12:54
I'm closing this since I believe it is caused by building with nightly. Feel free to reopen or comment here if I am wrong.

**Closed by dnut** 2024-09-24 12:54 UTC
